/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Connections */
        get: operations["list_connections_api_connections_get"];
        put?: never;
        /** Upsert Connection */
        post: operations["upsert_connection_api_connections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{connection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Connection */
        get: operations["get_connection_api_connections__connection_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{connection_id}/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest Probe
         * @description The latest probe, without touching the database; null if never probed.
         */
        get: operations["latest_probe_api_connections__connection_id__probe_get"];
        put?: never;
        /**
         * Probe
         * @description Probe the database now: what the analyzer can see.
         */
        post: operations["probe_api_connections__connection_id__probe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{connection_id}/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_connections__connection_id__capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{connection_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description Oldest first. A Run with a `thread_id` was started from chat.
         */
        get: operations["list_runs_api_connections__connection_id__runs_get"];
        put?: never;
        /**
         * Start Run
         * @description Run the analyzers and return the finished Run. Blocks until it finishes.
         */
        post: operations["start_run_api_connections__connection_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare Runs
         * @description What changed between two Runs of one Connection, over the scope both measured.
         */
        get: operations["compare_runs_api_runs_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description Everything the reports show of one Run: ranked observations, sizes, the workload
         *     ranking and what was skipped.
         */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Run */
        get: operations["export_run_api_runs__run_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{connection_id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Findings
         * @description The Connection's Findings with their latest Observation. Without `status`, every
         *     Finding but obsolete ones. A Finding with `unobserved_by` set asks "fixed?".
         */
        get: operations["list_findings_api_connections__connection_id__findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{connection_id}/findings/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Finding Status
         * @description Acknowledge, mark fixed or reopen a Finding; settles any "fixed?" prompt.
         */
        post: operations["set_finding_status_api_connections__connection_id__findings_status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{connection_id}/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Observations
         * @description One Finding's Observations, one per Run that saw it, oldest first.
         */
        get: operations["observations_api_connections__connection_id__observations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{connection_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Audit
         * @description Every statement executed or rejected, oldest first; optionally one Thread's.
         */
        get: operations["audit_api_connections__connection_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{connection_id}/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Threads
         * @description Latest activity first.
         */
        get: operations["list_threads_api_connections__connection_id__threads_get"];
        put?: never;
        /** Start Thread */
        post: operations["start_thread_api_connections__connection_id__threads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Thread */
        get: operations["get_thread_api_threads__thread_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads/{thread_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * History
         * @description The user's messages and the agent's final answers, in order.
         */
        get: operations["history_api_threads__thread_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads/{thread_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send
         * @description Run one Turn, streaming its AgentEvents as Server-Sent Events: the event name is the
         *     event's type, the data its JSON. The stream ends after `done`. Closing it cancels the
         *     Turn. 409 while the Thread has a Turn running; 503 when no model key is configured.
         */
        post: operations["send_api_threads__thread_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads/{thread_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel
         * @description Cancel the Thread's Turn in progress: its stream ends with `done`, `cancelled`.
         */
        post: operations["cancel_api_threads__thread_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads/{thread_id}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Thread Usage */
        get: operations["thread_usage_api_threads__thread_id__usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Monthly Usage
         * @description Every Thread's tokens and estimated cost in one calendar month. `cost_usd` is null
         *     when any request's cost is unknown.
         */
        get: operations["monthly_usage_api_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditEntry */
        AuditEntry: {
            /** Connection Id */
            connection_id: string;
            /** Purpose */
            purpose: string;
            /** Sql */
            sql: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "executed" | "rejected" | "failed";
            /** Reason */
            reason: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Row Count */
            row_count: number | null;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Thread Id */
            thread_id?: string | null;
            /** Plan Cost */
            plan_cost?: number | null;
            /** Plan Rows */
            plan_rows?: number | null;
        };
        /** Cancelled */
        Cancelled: {
            /** Cancelled */
            cancelled: boolean;
        };
        /**
         * Capability
         * @description What an adapter can do on a Connection. The agent gets a tool only for capabilities the
         *     Connection has.
         * @enum {string}
         */
        Capability: "probe" | "storage_stats" | "exact_counts" | "readonly_sql" | "workload";
        /**
         * CollectionKind
         * @enum {string}
         */
        CollectionKind: "table" | "partitioned_table" | "matview";
        /** CollectionRef */
        CollectionRef: {
            /** Namespace */
            namespace: string | null;
            /** Name */
            name: string;
            kind: components["schemas"]["CollectionKind"];
        };
        /**
         * Connection
         * @description A configured target: exactly one database. Holds a reference to the DSN, never the DSN.
         */
        Connection: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Adapter Kind */
            adapter_kind: string;
            /** Dsn Env */
            dsn_env: string;
            limits?: components["schemas"]["SessionLimits"];
            gate?: components["schemas"]["GateLimits"];
            /**
             * Alias Identifiers
             * @default false
             */
            alias_identifiers: boolean;
        };
        /**
         * ConnectionIn
         * @description A Connection to add, or to update by name. The DSN is never sent: `dsn_env` names the
         *     environment variable of the API process that holds it. Settings left out keep their
         *     current value (the default for a new Connection).
         */
        ConnectionIn: {
            /** Name */
            name: string;
            /** Dsn Env */
            dsn_env: string;
            limits?: components["schemas"]["SessionLimits"] | null;
            gate?: components["schemas"]["GateLimits"] | null;
            /** Alias Identifiers */
            alias_identifiers?: boolean | null;
        };
        /**
         * ConnectionInfo
         * @description A Connection as listed: whether this process's environment holds its DSN. Never the DSN
         *     or the variable's value.
         */
        ConnectionInfo: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Adapter Kind */
            adapter_kind: string;
            /** Dsn Env */
            dsn_env: string;
            limits?: components["schemas"]["SessionLimits"];
            gate?: components["schemas"]["GateLimits"];
            /**
             * Alias Identifiers
             * @default false
             */
            alias_identifiers: boolean;
            /**
             * Dsn Env Set
             * @default false
             */
            dsn_env_set: boolean;
        };
        /**
         * DeadTupleScan
         * @description A dead-tuple measurement that reads the table (pgstattuple_approx), not the counters.
         */
        DeadTupleScan: {
            /** Live Rows */
            live_rows: number;
            /** Dead Rows */
            dead_rows: number;
            /** Dead Percent */
            dead_percent: number;
            /** Free Percent */
            free_percent: number;
        };
        /**
         * ErrorBody
         * @description Every error: a stable machine `code`, a `message` to show, and `details` when there is
         *     more to say.
         */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * Finding
         * @description A problem or fact about one subject, with an identity stable across Runs.
         *     `unobserved_by` is the latest Run whose scope covered the subject but did not observe the
         *     Finding: it asks the engineer "fixed?". It is never answered automatically.
         */
        Finding: {
            /** Connection Id */
            connection_id: string;
            /** Fingerprint */
            fingerprint: string;
            /**
             * Category
             * @enum {string}
             */
            category: "size" | "slow_query" | "missing_index" | "unused_index" | "duplicate_index" | "invalid_index" | "bloat" | "stale_stats" | "hotspot" | "config";
            /** Subject */
            subject: string;
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "acknowledged" | "fixed" | "obsolete";
            /** First Seen Run */
            first_seen_run: string;
            /** Last Seen Run */
            last_seen_run: string;
            /** Unobserved By */
            unobserved_by?: string | null;
            /** Collection */
            collection?: string | null;
            /** Covered By */
            covered_by?: ("inventory" | "workload" | "index_advice" | "hotspot") | null;
        };
        /**
         * FindingView
         * @description A Finding with what the latest Run to observe it saw: its severity, title, evidence and
         *     recommendation now.
         */
        FindingView: {
            finding: components["schemas"]["Finding"];
            latest: components["schemas"]["Observation"];
        };
        /**
         * GateLimits
         * @description EXPLAIN gate limits; a statement whose plan exceeds any of them is not run.
         */
        GateLimits: {
            /**
             * Max Total Cost
             * @default 2000000
             */
            max_total_cost: number;
            /**
             * Max Result Rows
             * @default 10000
             */
            max_result_rows: number;
            /**
             * Max Scan Rows
             * @default 50000000
             */
            max_scan_rows: number;
        };
        /** Health */
        Health: {
            /** Version */
            version: string;
            /** Chat Available */
            chat_available: boolean;
        };
        /**
         * Maintenance
         * @description Activity counters and vacuum/analyze recency of one collection (a partitioned table sums
         *     its leaf partitions and takes the oldest timestamp; None if any leaf never had it).
         */
        Maintenance: {
            /** Live Rows */
            live_rows: number;
            /** Dead Rows */
            dead_rows: number;
            /** Modified Since Analyze */
            modified_since_analyze: number;
            /** Last Vacuum */
            last_vacuum: string | null;
            /** Last Analyze */
            last_analyze: string | null;
            /** Autovacuum Disabled */
            autovacuum_disabled: boolean;
        };
        /** MessageIn */
        MessageIn: {
            /** Message */
            message: string;
        };
        /**
         * Observation
         * @description What one Run saw for one Finding.
         */
        Observation: {
            /** Run Id */
            run_id: string;
            /** Fingerprint */
            fingerprint: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "low" | "medium" | "high";
            /** Title */
            title: string;
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            };
            /** Recommendation */
            recommendation: string | null;
            /** Ddl */
            ddl: string | null;
        };
        /** Privileges */
        Privileges: {
            /** Pg Monitor */
            pg_monitor: boolean;
            /** Pg Read All Stats */
            pg_read_all_stats: boolean;
            /** Readable Tables */
            readable_tables: number;
            /** Unreadable Tables */
            unreadable_tables: string[];
            /**
             * Azure Sys Connect
             * @default false
             */
            azure_sys_connect: boolean;
        };
        /**
         * ProbeResult
         * @description What the analyzer can see on a Connection.
         */
        ProbeResult: {
            /** Server Version Num */
            server_version_num: number;
            /** Server Version */
            server_version: string;
            /** In Recovery */
            in_recovery: boolean;
            /**
             * Host Type
             * @enum {string}
             */
            host_type: "self_managed" | "azure_flexible";
            /** Extensions */
            extensions: {
                [key: string]: string;
            };
            privileges: components["schemas"]["Privileges"];
            /** Settings */
            settings: {
                [key: string]: string | null;
            };
            stats: components["schemas"]["StatsFreshness"];
            /**
             * Taken At
             * Format: date-time
             */
            taken_at: string;
            /** Extension Schemas */
            extension_schemas?: {
                [key: string]: string;
            };
        };
        /**
         * Run
         * @description One execution of analyzers against a Connection. `scope` lists, per analyzer, the
         *     collections actually measured; `skipped` those planned but not measured, with the reason.
         */
        Run: {
            /** Id */
            id: string;
            /** Connection Id */
            connection_id: string;
            /** Thread Id */
            thread_id: string | null;
            /** Scope */
            scope: {
                [key: string]: components["schemas"]["CollectionRef"][];
            };
            /** Skipped */
            skipped: {
                [key: string]: [
                    components["schemas"]["CollectionRef"],
                    string
                ][];
            };
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "complete" | "partial" | "failed";
        };
        /**
         * RunComparison
         * @description `shared` is, per analyzer, the collections both Runs measured; `not_compared` those only
         *     one of them measured (including ones the other skipped). Size changes are largest first;
         *     `appeared` and `disappeared` are problem Findings, by fingerprint.
         */
        RunComparison: {
            /** Before */
            before: string;
            /** After */
            after: string;
            /** Shared */
            shared: {
                [key: string]: string[];
            };
            /** Not Compared */
            not_compared: {
                [key: string]: string[];
            };
            /** Size Changes */
            size_changes: components["schemas"]["SizeChange"][];
            /** Appeared */
            appeared: string[];
            /** Disappeared */
            disappeared: string[];
        };
        /**
         * RunIn
         * @description A deterministic Run: no model. `collections` targets inventory at those tables
         *     (schema-qualified, or bare when unambiguous) and `exact_counts` counts their rows, each only
         *     where the EXPLAIN gate allows. `min_stats_window_hours` is how young workload statistics
         *     may be before ranking is refused (default 1 h). Options no chosen analyzer takes are
         *     refused.
         */
        RunIn: {
            /** Analyzers */
            analyzers?: string[];
            /** Collections */
            collections?: string[] | null;
            /**
             * Exact Counts
             * @default false
             */
            exact_counts: boolean;
            /** Min Stats Window Hours */
            min_stats_window_hours?: number | null;
        };
        /**
         * RunView
         * @description `observations` in rank order, most severe first. `storage` is None when the Run did not
         *     include inventory, else largest first; `workload` is None when it did not include workload.
         *     `skipped` lists whole collections first, then measurements in `storage` order.
         */
        RunView: {
            connection: components["schemas"]["Connection"];
            run: components["schemas"]["Run"];
            /** Observations */
            observations: components["schemas"]["Observation"][];
            /** Storage */
            storage: components["schemas"]["StorageStats"][] | null;
            workload: components["schemas"]["WorkloadReport"] | null;
            /** Skipped */
            skipped: components["schemas"]["Skipped"][];
        };
        /** SessionLimits */
        SessionLimits: {
            /**
             * Statement Timeout
             * @default 30s
             */
            statement_timeout: string;
            /**
             * Lock Timeout
             * @default 1s
             */
            lock_timeout: string;
            /**
             * Work Mem
             * @default 32MB
             */
            work_mem: string;
        };
        /** SizeChange */
        SizeChange: {
            /** Collection */
            collection: string;
            /** Before Bytes */
            before_bytes: number;
            /** After Bytes */
            after_bytes: number;
            /** Delta Bytes */
            delta_bytes: number;
        };
        /**
         * Skipped
         * @description A collection a Run planned but did not measure (`measurement` None), or one measurement it
         *     did not take on a collection it did measure.
         */
        Skipped: {
            /**
             * Analyzer
             * @enum {string}
             */
            analyzer: "inventory" | "workload" | "index_advice" | "hotspot";
            /** Collection */
            collection: string;
            /** Measurement */
            measurement: string | null;
            /** Reason */
            reason: string;
        };
        /** StatsFreshness */
        StatsFreshness: {
            /** Database Stats Reset */
            database_stats_reset: string | null;
            /** Statements Stats Reset */
            statements_stats_reset: string | null;
            /** Never Analyzed Tables */
            never_analyzed_tables: number;
            /** Oldest Analyze */
            oldest_analyze: string | null;
        };
        /** StatusIn */
        StatusIn: {
            /** Fingerprint */
            fingerprint: string;
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "acknowledged" | "fixed";
        };
        /**
         * StorageStats
         * @description Size of one collection. `row_count` is None when the store has no estimate yet.
         *     `skipped` names measurements planned for this collection but not taken, with the reason
         *     (e.g. an exact count the EXPLAIN gate refused); the collection itself was measured.
         */
        StorageStats: {
            ref: components["schemas"]["CollectionRef"];
            /** Row Count */
            row_count: number | null;
            /**
             * Row Count Method
             * @enum {string}
             */
            row_count_method: "exact" | "estimate" | "sample";
            /** Data Bytes */
            data_bytes: number;
            /** Index Bytes */
            index_bytes: number;
            /** Toast Bytes */
            toast_bytes: number | null;
            /** Total Bytes */
            total_bytes: number;
            /** Partitions */
            partitions?: number | null;
            maintenance?: components["schemas"]["Maintenance"] | null;
            dead_tuple_scan?: components["schemas"]["DeadTupleScan"] | null;
            /** Skipped */
            skipped?: {
                [key: string]: string;
            };
        };
        /**
         * Thread
         * @description A conversation with the agent, bound to one Connection for its whole life.
         *     `last_active_at` is when its latest Turn started, and `preview` the start of its first
         *     message: both None until its first Turn (and for Threads from before they were kept).
         */
        Thread: {
            /** Id */
            id: string;
            /** Connection Id */
            connection_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Active At */
            last_active_at?: string | null;
            /** Preview */
            preview?: string | null;
        };
        /**
         * ThreadMessage
         * @description One message of a Thread's history: the user's, or the agent's final answer.
         */
        ThreadMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "agent";
            /** Text */
            text: string;
        };
        /** Usage */
        Usage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "usage";
            /** Model */
            model: string;
            /** Input Tokens */
            input_tokens: number;
            /** Cached Tokens */
            cached_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cost Usd */
            cost_usd: number | null;
        };
        /**
         * WorkloadItem
         * @description One distinct statement of the workload, ranked. `fingerprint` is a hash of the
         *     normalized text, never the server's query id, so it holds across versions.
         */
        WorkloadItem: {
            /** Fingerprint */
            fingerprint: string;
            /** Text */
            text: string;
            /** Calls */
            calls: number;
            /** Total Ms */
            total_ms: number;
            /** Mean Ms */
            mean_ms: number;
            /** Rows */
            rows: number;
            /** Shared Blks Read */
            shared_blks_read: number;
            /** Temp Blks Written */
            temp_blks_written: number;
            /** Share Of Time */
            share_of_time: number;
            /** Ranked By */
            ranked_by: string[];
        };
        /**
         * WorkloadReport
         * @description What the workload part of a Run found. `items` is empty and `refused` says why when the
         *     statistics cannot be ranked; `source` is None when the Connection has none.
         */
        WorkloadReport: {
            /** Source */
            source: ("pg_stat_statements" | "azure_query_store") | null;
            /** Stats Reset */
            stats_reset: string | null;
            /** Window Seconds */
            window_seconds: number | null;
            /** Items */
            items: components["schemas"]["WorkloadItem"][];
            /** Statements */
            statements: number;
            /** Total Ms */
            total_ms: number;
            /** Excluded */
            excluded: {
                [key: string]: number;
            };
            /** Warnings */
            warnings: string[];
            /** Refused */
            refused?: string | null;
            /** Enable Steps */
            enable_steps?: string[];
        };
        /**
         * Done
         * @description Last event of every Turn. `ok` is False when the Turn ended on an Error or was
         *     cancelled; `cancelled` tells the two apart. `answer` is what was answered before it ended.
         */
        Done: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "done";
            /** Thread Id */
            thread_id: string;
            /** Answer */
            answer: string;
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /**
             * Cancelled
             * @default false
             */
            cancelled: boolean;
        };
        /** Error */
        Error: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
            /** Message */
            message: string;
        };
        /** LimitReached */
        LimitReached: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "limit_reached";
            /**
             * Limit
             * @enum {string}
             */
            limit: "tokens" | "tool_calls" | "queries";
            /** Used */
            used: number;
            /** Max */
            max: number;
        };
        /** RunFinished */
        RunFinished: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run_finished";
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
        };
        /** SqlExecuted */
        SqlExecuted: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "sql_executed";
            /** Sql */
            sql: string;
            /** Purpose */
            purpose: string;
            /** Duration Ms */
            duration_ms: number | null;
            /** Row Count */
            row_count: number | null;
            /** Plan Cost */
            plan_cost: number | null;
        };
        /** SqlRejected */
        SqlRejected: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "sql_rejected";
            /** Sql */
            sql: string;
            /** Purpose */
            purpose: string;
            /** Reason */
            reason: string;
        };
        /** SubagentFinished */
        SubagentFinished: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "subagent_finished";
            /** Call Id */
            call_id: string;
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
        };
        /**
         * SubagentStarted
         * @description The orchestrator delegated to a subagent through tool call `call_id`.
         */
        SubagentStarted: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "subagent_started";
            /** Call Id */
            call_id: string;
            /** Name */
            name: string;
        };
        /** Token */
        Token: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "token";
            /** Text */
            text: string;
        };
        /** ToolFinished */
        ToolFinished: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tool_finished";
            /** Call Id */
            call_id: string;
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
            /** Summary */
            summary: string;
        };
        /** ToolStarted */
        ToolStarted: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tool_started";
            /** Call Id */
            call_id: string;
            /** Name */
            name: string;
            /** Args */
            args: {
                [key: string]: unknown;
            };
        };
        AgentEvent: components["schemas"]["Token"] | components["schemas"]["ToolStarted"] | components["schemas"]["ToolFinished"] | components["schemas"]["SubagentStarted"] | components["schemas"]["SubagentFinished"] | components["schemas"]["SqlExecuted"] | components["schemas"]["SqlRejected"] | components["schemas"]["RunFinished"] | components["schemas"]["LimitReached"] | components["schemas"]["Usage"] | components["schemas"]["Error"] | components["schemas"]["Done"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    list_connections_api_connections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionInfo"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    upsert_connection_api_connections_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionInfo"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_connection_api_connections__connection_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionInfo"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    latest_probe_api_connections__connection_id__probe_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeResult"] | null;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    probe_api_connections__connection_id__probe_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeResult"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    capabilities_api_connections__connection_id__capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capability"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_runs_api_connections__connection_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    start_run_api_connections__connection_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    compare_runs_api_runs_compare_get: {
        parameters: {
            query: {
                before: string;
                after: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunComparison"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    export_run_api_runs__run_id__export_get: {
        parameters: {
            query?: {
                format?: "md" | "json";
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The report, as a download. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/markdown": unknown;
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_findings_api_connections__connection_id__findings_get: {
        parameters: {
            query?: {
                status?: ("open" | "acknowledged" | "fixed" | "obsolete")[] | null;
            };
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingView"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    set_finding_status_api_connections__connection_id__findings_status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Finding"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    observations_api_connections__connection_id__observations_get: {
        parameters: {
            query: {
                fingerprint: string;
            };
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Observation"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    audit_api_connections__connection_id__audit_get: {
        parameters: {
            query?: {
                thread_id?: string | null;
            };
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntry"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_threads_api_connections__connection_id__threads_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thread"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    start_thread_api_connections__connection_id__threads_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thread"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_thread_api_threads__thread_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thread"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    history_api_threads__thread_id__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadMessage"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    send_api_threads__thread_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageIn"];
            };
        };
        responses: {
            /** @description The Turn's AgentEvents, one per Server-Sent Event. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["AgentEvent"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    cancel_api_threads__thread_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cancelled"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    thread_usage_api_threads__thread_id__usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Usage"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    monthly_usage_api_usage_get: {
        parameters: {
            query?: {
                /** @description YYYY-MM (UTC); default: this month */
                month?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Usage"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
